trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.15.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
  displayName: 'Install Yarn'

- script: |
    yarn install
  displayName: 'Install Dependencies'

- script: |
    yarn build
  displayName: 'Build Project'

- task: CopyFiles@2
  inputs:
    contents: 'build/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files to Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Build Artifacts'
