trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'  # Hoặc 'ubuntu-latest' cho Android

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
  displayName: 'Install Yarn'

- script: |
    yarn install
  displayName: 'Install Dependencies'



- script: |
    yarn android  # Hoặc yarn ios nếu bạn đang build cho iOS
  displayName: 'Build React Native Project'

- task: CopyFiles@2
  inputs:
    contents: 'build/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files to Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Build Artifacts'
