trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # Sử dụng ubuntu nếu bạn muốn build cho Android

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
  displayName: 'Install Yarn'

- script: |
    yarn install
  displayName: 'Install Dependencies'


# azure-pipelines.yml
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseAndroidSdk@1
  inputs:
    versionSpec: '30.x'

- script: |
    sdkmanager --update
    sdkmanager "system-images;android-30;google_apis;x86"
    sdkmanager "platform-tools"
    sdkmanager "platforms;android-30"
    echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel"
    emulator -avd test -no-skin -no-audio -no-boot-anim &
    adb wait-for-device
    adb shell input keyevent 82
  displayName: 'Set up Android Emulator'

- script: |
    chmod +x ./android/gradlew  # Cấp quyền thực thi cho gradlew
    yarn android
  displayName: 'Build React Native Project'

- task: CopyFiles@2
  inputs:
    contents: 'build/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files to Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Build Artifacts'
